sudo: false
language: node_js
node_js:
<<<<<<< HEAD
  - stable

cache:
  yarn: true
  directories:
    - node_modules

script:
  - yarn test

=======
  - "11.10"
cache: yarn
script:
  - yarn test

after_success:
  - npm run build
  - npm run semantic-release
>>>>>>> 318db104c7ba4f279392111c11397d2f053594e7
branches:
  only:
    - master
    - v1-stable
